/** Kayla Chea: I wrote this class to keep track of constants. **/

package edu.uw.jatn.genshinguide

const val BASE_URL = "https://impact.moe/api/"
val CHAR_NAME: Array<String> =
    arrayOf(
        "albedo",
        "aloy",
        "amber",
        "ayaka",
        "barbara",
        "beidou",
        "bennett",
        "chongyun",
        "dainsleif",
        "diluc",
        "diona",
        "eula",
        "fischl",
        "ganyu",
        "gorou",
        "hu-tao",
        "itto",
        "jean",
        "kaeya",
        "kazuha",
        "keqing",
        "klee",
        "kokomi",
        "lisa",
        "mimi",
        "mona",
        "ningguang",
        "noelle",
        "paimon",
        "qiqi",
        "razor",
        "rosaria",
        "sara",
        "sayu",
        "scaramouche",
        "shenli",
        "shogun",
        "sucrose",
        "tartaglia",
        "thoma",
        "traveler-anemo",
        "traveler-electro",
        "traveler-geo",
        "venti",
        "xiangling",
        "xiao",
        "xingqiu",
        "xinyan",
        "yanfei",
        "yaoyao",
        "yoimiya",
        "yunjin",
        "zhongli"
    )